# Используем Maven с Java 21
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Копирование файлов проекта
COPY pom.xml .
COPY src ./src

# Сборка приложения
RUN mvn clean package -DskipTests

# Этап запуска с Java 21
FROM eclipse-temurin:21-jre
WORKDIR /app

# Копирование собранного jar файла
COPY --from=build /app/target/*.jar app.jar

# Порт приложения
EXPOSE 8080

# Запуск приложения
ENTRYPOINT ["java", "-jar", "app.jar"]